version: '3'
services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - server
            - front 
        restart: always
        ports:
            - "80:80"
            
    postgres:
        container_name: postgres_db
        image: postgres:latest
        env_file:
            - ./server/.env
        #ports:
        #    - "5432:5432"
        volumes:
            - "/tmp/postgres_data:/var/lib/postgresql/data"
        #volumes:
        #    - "/tmp/postgres_data:/var/lib/postgresql/data"


    server:
        container_name: transcendance_api
        depends_on:
            - postgres
        build: 
            context: ./server/
            dockerfile: Dockerfile
        env_file:
            - ./server/.env

        volumes:
            - "./server/:/var/www/html/app" 
            - /var/www/html/app/node_modules/
            - /var/www/html/app/dist
    
    front:
        container_name: transcendance_front
        depends_on:
            - server
        build: 
            context: ./web/
            dockerfile: Dockerfile
        volumes:
            - "./web/:/var/www/html/app" 
            - /var/www/html/app/node_modules/
            - /var/www/html/app/.next
