version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - "5432:5432"
        env_file:
            - "./.env"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - pong-network
networks:
    pong-network:
